import { useState, useEffect, useRef } from 'react'
import { useQuery, useMutation } from '@tanstack/react-query'
import { consultationsApi } from '@/api/consultations'
import { Save, CheckCircle, Loader2, Download, CloudCheck } from 'lucide-react'
import toast from 'react-hot-toast'

interface Props {
  consultationId: string
}

export default function SOAPEditor({ consultationId }: Props) {
  const [fields, setFields] = useState({ subjective: '', objective: '', assessment: '', plan: '' })
  const [synced, setSynced] = useState(false)
  const [isAutoSaving, setIsAutoSaving] = useState(false)
  const lastSavedFields = useRef(JSON.stringify(fields))

  const { isLoading: reportLoading } = useQuery({
    queryKey: ['report', consultationId],
    queryFn: () => consultationsApi.getReport(consultationId),
    onSuccess: (data: any) => {
      if (data && !data.error) {
        const loaded = {
          subjective: data.subjective || '',
          objective: data.objective || '',
          assessment: data.assessment || '',
          plan: data.plan || '',
        }
        setFields(loaded)
        lastSavedFields.current = JSON.stringify(loaded)
        setSynced(true)
      }
    },
  } as any)

  const saveMut = useMutation({
    mutationFn: () => consultationsApi.updateReport(consultationId, fields),
    onSuccess: () => {
      lastSavedFields.current = JSON.stringify(fields)
      setIsAutoSaving(false)
    },
    onError: () => setIsAutoSaving(false),
  })

  // 10s Auto-save Logic
  useEffect(() => {
    const timer = setInterval(() => {
      const current = JSON.stringify(fields)
      if (current !== lastSavedFields.current && fields.subjective.length > 0) {
        setIsAutoSaving(true)
        saveMut.mutate()
      }
    }, 10000)

    return () => clearInterval(timer)
  }, [fields, saveMut])

  const generateMut = useMutation({
    mutationFn: () => (consultationsApi as any).generateSoap?.(consultationId) ?? Promise.reject('Not implemented'),
    onSuccess: (data: any) => {
      if (data && !data.error) {
        const generated = { subjective: data.subjective || '', objective: data.objective || '', assessment: data.assessment || '', plan: data.plan || '' }
        setFields(generated)
        lastSavedFields.current = JSON.stringify(generated)
        setSynced(true)
        toast.success('SOAP note generated by AI')
      }
    },
    onError: () => toast.error('SOAP generation failed'),
  })

  const approveMut = useMutation({
    mutationFn: () => consultationsApi.approveReport(consultationId, ''),
    onSuccess: () => toast.success('Report approved and locked'),
    onError: () => toast.error('Failed to approve report'),
  })

  const exportMut = useMutation({
    mutationFn: () => apiClient.get(`/consultations/${consultationId}/export`).then(r => r.data),
    onSuccess: (data) => {
      const blob = new Blob([data.content], { type: 'text/plain' })
      const url = window.URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = data.filename
      a.click()
      toast.success('Report exported successfully')
    },
    onError: () => toast.error('Export failed'),
  })

  const SECTIONS = [
    { key: 'subjective', label: 'S — Subjective', color: '#5a3fad', placeholder: "Patient's chief complaint, history, and symptoms…" },
    { key: 'objective', label: 'O — Objective', color: '#0e7c4a', placeholder: 'Physical exam findings, vitals, and measurements…' },
    { key: 'assessment', label: 'A — Assessment', color: '#e67e22', placeholder: 'Clinical diagnosis and differential diagnoses…' },
    { key: 'plan', label: 'P — Plan', color: '#2980b9', placeholder: 'Treatment plan, medications, and follow-up…' },
  ]

  if (reportLoading) return <div style={{ textAlign: 'center', padding: 40, color: 'var(--text-3)' }}><Loader2 size={24} style={{ animation: 'spin 1s linear infinite' }} /></div>

  return (
    <div>
      <div style={{ display: 'flex', justifyContent: 'flex-end', marginBottom: 12 }}>
        {isAutoSaving && (
          <div style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: 11, color: 'var(--text-3)' }}>
            <Loader2 size={12} className="animate-spin" /> Auto-saving draft…
          </div>
        )}
        {!isAutoSaving && (
          <div style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: 11, color: '#0e7c4a' }}>
             All changes saved
          </div>
        )}
      </div>

      {!synced && (
        <div style={{ marginBottom: 20, padding: '14px 18px', background: '#5a3fad10', border: '1px solid #5a3fad30', borderRadius: 10, display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
          <span style={{ fontSize: 13, color: 'var(--text-2)' }}>No SOAP note found. Generate one from the consultation transcript.</span>
          <button
            onClick={() => generateMut.mutate()}
            disabled={generateMut.isPending}
            style={{ padding: '7px 16px', background: '#5a3fad', color: '#fff', border: 'none', borderRadius: 7, fontSize: 12.5, fontWeight: 500, cursor: 'pointer' }}
          >
            {generateMut.isPending ? 'Generating…' : '✦ Generate with AI'}
          </button>
        </div>
      )}

      <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
        {SECTIONS.map(({ key, label, color, placeholder }) => (
          <div key={key}>
            <label style={{ display: 'block', fontSize: 12, fontWeight: 700, color, marginBottom: 6, textTransform: 'uppercase', letterSpacing: '0.05em' }}>{label}</label>
            <textarea
              value={fields[key as keyof typeof fields]}
              onChange={(e) => setFields((f) => ({ ...f, [key]: e.target.value }))}
              placeholder={placeholder}
              className="form-control"
              rows={5}
              style={{ resize: 'vertical', fontFamily: 'inherit', lineHeight: 1.6 }}
            />
          </div>
        ))}
      </div>

      <div style={{ display: 'flex', gap: 10, justifyContent: 'flex-end', marginTop: 20 }}>
        <button
          onClick={() => exportMut.mutate()}
          style={{ display: 'flex', alignItems: 'center', gap: 6, padding: '9px 18px', background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 8, fontSize: 13, fontWeight: 500, cursor: 'pointer', color: 'var(--text-1)' }}
        >
          <Download size={14} /> Export Report
        </button>
        <button
          onClick={() => saveMut.mutate()}
          disabled={saveMut.isPending}
          style={{ display: 'flex', alignItems: 'center', gap: 6, padding: '9px 18px', background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 8, fontSize: 13, fontWeight: 500, cursor: 'pointer', color: 'var(--text-1)' }}
        >
          <Save size={14} /> {saveMut.isPending ? 'Saving…' : 'Save Draft'}
        </button>
        <button
          onClick={() => approveMut.mutate()}
          disabled={approveMut.isPending}
          style={{ display: 'flex', alignItems: 'center', gap: 6, padding: '9px 18px', background: '#0e7c4a', color: '#fff', border: 'none', borderRadius: 8, fontSize: 13, fontWeight: 500, cursor: 'pointer' }}
        >
          <CheckCircle size={14} /> {approveMut.isPending ? 'Approving…' : 'Approve & Finalize'}
        </button>
      </div>
    </div>
  )
}
